# Makefile generated by XPJ for linux64
-include Makefile.custom
ProjectName = flexDevice
flexDevice_cppfiles   += ./../../../src/device/PhysXDevice.cpp
flexDevice_cppfiles   += ./../../../src/device/flexDevice.cpp

flexDevice_cpp_release_dep    = $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(flexDevice_cppfiles)))))
flexDevice_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(flexDevice_ccfiles)))))
flexDevice_c_release_dep      = $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(flexDevice_cfiles)))))
flexDevice_release_dep      = $(flexDevice_cpp_release_dep) $(flexDevice_cc_release_dep) $(flexDevice_c_release_dep)
-include $(flexDevice_release_dep)
flexDevice_cpp_debug_dep    = $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(flexDevice_cppfiles)))))
flexDevice_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(flexDevice_ccfiles)))))
flexDevice_c_debug_dep      = $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(flexDevice_cfiles)))))
flexDevice_debug_dep      = $(flexDevice_cpp_debug_dep) $(flexDevice_cc_debug_dep) $(flexDevice_c_debug_dep)
-include $(flexDevice_debug_dep)
flexDevice_release_hpaths    := 
flexDevice_release_hpaths    += ./../../../../../../external/CUDA/8.0.44-linux/include
flexDevice_release_hpaths    += ./../../../../../../external/CUDA/8.0.44-linux/extras/cupti/include
flexDevice_release_hpaths    += ./../../..
flexDevice_release_lpaths    := 
flexDevice_release_lpaths    += ./../../../../../../external/CUDA/8.0.44-linux/lib64
flexDevice_release_defines   := $(flexDevice_custom_defines)
flexDevice_release_libraries := 
flexDevice_release_common_cflags	:= $(flexDevice_custom_cflags)
flexDevice_release_common_cflags    += -MMD
flexDevice_release_common_cflags    += $(addprefix -D, $(flexDevice_release_defines))
flexDevice_release_common_cflags    += $(addprefix -I, $(flexDevice_release_hpaths))
flexDevice_release_common_cflags  += -m64
flexDevice_release_cflags	:= $(flexDevice_release_common_cflags)
flexDevice_release_cflags  += -Wall -std=c++0x -fPIC -fpermissive -fno-strict-aliasing
flexDevice_release_cflags  += -O3 -ffast-math -DNDEBUG
flexDevice_release_cppflags	:= $(flexDevice_release_common_cflags)
flexDevice_release_cppflags  += -Wall -std=c++0x -fPIC -fpermissive -fno-strict-aliasing
flexDevice_release_cppflags  += -O3 -ffast-math -DNDEBUG
flexDevice_release_lflags    := $(flexDevice_custom_lflags)
flexDevice_release_lflags    += $(addprefix -L, $(flexDevice_release_lpaths))
flexDevice_release_lflags    += -Wl,--start-group $(addprefix -l, $(flexDevice_release_libraries)) -Wl,--end-group
flexDevice_release_lflags  += -m64
flexDevice_release_objsdir  = $(OBJS_DIR)/flexDevice_release
flexDevice_release_cpp_o    = $(addprefix $(flexDevice_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(flexDevice_cppfiles)))))
flexDevice_release_cc_o    = $(addprefix $(flexDevice_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(flexDevice_ccfiles)))))
flexDevice_release_c_o      = $(addprefix $(flexDevice_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(flexDevice_cfiles)))))
flexDevice_release_obj      = $(flexDevice_release_cpp_o) $(flexDevice_release_cc_o) $(flexDevice_release_c_o)
flexDevice_release_bin      := ./../../../lib/linux64/NvFlexDeviceRelease_x64.a

clean_flexDevice_release: 
	@$(ECHO) clean flexDevice release
	@$(RMDIR) $(flexDevice_release_objsdir)
	@$(RMDIR) $(flexDevice_release_bin)
	@$(RMDIR) $(DEPSDIR)/flexDevice/release

build_flexDevice_release: postbuild_flexDevice_release
postbuild_flexDevice_release: mainbuild_flexDevice_release
mainbuild_flexDevice_release: prebuild_flexDevice_release $(flexDevice_release_bin)
prebuild_flexDevice_release:

$(flexDevice_release_bin): $(flexDevice_release_obj) 
	mkdir -p `dirname ./../../../lib/linux64/NvFlexDeviceRelease_x64.a`
	@$(AR) rcs $(flexDevice_release_bin) $(flexDevice_release_obj)
	$(ECHO) building $@ complete!

flexDevice_release_DEPDIR = $(dir $(@))/$(*F)
$(flexDevice_release_cpp_o): $(flexDevice_release_objsdir)/%.o:
	$(ECHO) flexDevice: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(flexDevice_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cppfiles))))))
	cp $(flexDevice_release_DEPDIR).d $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cppfiles))))).P; \
	  rm -f $(flexDevice_release_DEPDIR).d

$(flexDevice_release_cc_o): $(flexDevice_release_objsdir)/%.o:
	$(ECHO) flexDevice: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(flexDevice_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_ccfiles))))))
	cp $(flexDevice_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_ccfiles))))).release.P; \
	  rm -f $(flexDevice_release_DEPDIR).d

$(flexDevice_release_c_o): $(flexDevice_release_objsdir)/%.o:
	$(ECHO) flexDevice: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(flexDevice_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cfiles))))))
	cp $(flexDevice_release_DEPDIR).d $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/flexDevice/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_release_objsdir),, $@))), $(flexDevice_cfiles))))).P; \
	  rm -f $(flexDevice_release_DEPDIR).d

flexDevice_debug_hpaths    := 
flexDevice_debug_hpaths    += ./../../../../../../external/CUDA/8.0.44-linux/include
flexDevice_debug_hpaths    += ./../../../../../../external/CUDA/8.0.44-linux/extras/cupti/include
flexDevice_debug_hpaths    += ./../../..
flexDevice_debug_lpaths    := 
flexDevice_debug_lpaths    += ./../../../../../../external/CUDA/8.0.44-linux/lib64
flexDevice_debug_defines   := $(flexDevice_custom_defines)
flexDevice_debug_libraries := 
flexDevice_debug_common_cflags	:= $(flexDevice_custom_cflags)
flexDevice_debug_common_cflags    += -MMD
flexDevice_debug_common_cflags    += $(addprefix -D, $(flexDevice_debug_defines))
flexDevice_debug_common_cflags    += $(addprefix -I, $(flexDevice_debug_hpaths))
flexDevice_debug_common_cflags  += -m64
flexDevice_debug_cflags	:= $(flexDevice_debug_common_cflags)
flexDevice_debug_cflags  += -Wall -std=c++0x -fPIC -fpermissive -fno-strict-aliasing
flexDevice_debug_cflags  += -g -O0
flexDevice_debug_cppflags	:= $(flexDevice_debug_common_cflags)
flexDevice_debug_cppflags  += -Wall -std=c++0x -fPIC -fpermissive -fno-strict-aliasing
flexDevice_debug_cppflags  += -g -O0
flexDevice_debug_lflags    := $(flexDevice_custom_lflags)
flexDevice_debug_lflags    += $(addprefix -L, $(flexDevice_debug_lpaths))
flexDevice_debug_lflags    += -Wl,--start-group $(addprefix -l, $(flexDevice_debug_libraries)) -Wl,--end-group
flexDevice_debug_lflags  += -m64
flexDevice_debug_objsdir  = $(OBJS_DIR)/flexDevice_debug
flexDevice_debug_cpp_o    = $(addprefix $(flexDevice_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(flexDevice_cppfiles)))))
flexDevice_debug_cc_o    = $(addprefix $(flexDevice_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(flexDevice_ccfiles)))))
flexDevice_debug_c_o      = $(addprefix $(flexDevice_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(flexDevice_cfiles)))))
flexDevice_debug_obj      = $(flexDevice_debug_cpp_o) $(flexDevice_debug_cc_o) $(flexDevice_debug_c_o)
flexDevice_debug_bin      := ./../../../lib/linux64/NvFlexDeviceDebug_x64.a

clean_flexDevice_debug: 
	@$(ECHO) clean flexDevice debug
	@$(RMDIR) $(flexDevice_debug_objsdir)
	@$(RMDIR) $(flexDevice_debug_bin)
	@$(RMDIR) $(DEPSDIR)/flexDevice/debug

build_flexDevice_debug: postbuild_flexDevice_debug
postbuild_flexDevice_debug: mainbuild_flexDevice_debug
mainbuild_flexDevice_debug: prebuild_flexDevice_debug $(flexDevice_debug_bin)
prebuild_flexDevice_debug:

$(flexDevice_debug_bin): $(flexDevice_debug_obj) 
	mkdir -p `dirname ./../../../lib/linux64/NvFlexDeviceDebug_x64.a`
	@$(AR) rcs $(flexDevice_debug_bin) $(flexDevice_debug_obj)
	$(ECHO) building $@ complete!

flexDevice_debug_DEPDIR = $(dir $(@))/$(*F)
$(flexDevice_debug_cpp_o): $(flexDevice_debug_objsdir)/%.o:
	$(ECHO) flexDevice: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(flexDevice_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cppfiles))))))
	cp $(flexDevice_debug_DEPDIR).d $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cppfiles))))).P; \
	  rm -f $(flexDevice_debug_DEPDIR).d

$(flexDevice_debug_cc_o): $(flexDevice_debug_objsdir)/%.o:
	$(ECHO) flexDevice: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(flexDevice_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_ccfiles))))))
	cp $(flexDevice_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_ccfiles))))).debug.P; \
	  rm -f $(flexDevice_debug_DEPDIR).d

$(flexDevice_debug_c_o): $(flexDevice_debug_objsdir)/%.o:
	$(ECHO) flexDevice: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(flexDevice_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cfiles))))))
	cp $(flexDevice_debug_DEPDIR).d $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(flexDevice_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/flexDevice/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(flexDevice_debug_objsdir),, $@))), $(flexDevice_cfiles))))).P; \
	  rm -f $(flexDevice_debug_DEPDIR).d

clean_flexDevice:  clean_flexDevice_release clean_flexDevice_debug
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
